import type {
  AlertRecord,
  Announcement,
  AppUser,
  AttendanceSummary,
  AuditLogEntry,
  FaceEvent,
  FingerprintEvent,
  IncentiveRecord,
  LeaveRecord,
  LineAssignmentRecord,
  OvertimeRecord,
  ProductionLineRecord,
  ReportSeries,
  SmartInsight,
  SystemSettings,
  TransferLog,
  ValidationRecord,
  WorkerProfile,
} from "./types";

export const mockUsers: AppUser[] = [
  {
    id: "user-admin",
    name: "Malithi Jayasinghe",
    role: "admin",
    title: "Factory Systems Administrator",
    department: "Operations",
    initials: "MJ",
  },
  {
    id: "user-supervisor",
    name: "Dhanushka Perera",
    role: "supervisor",
    title: "Floor Supervisor",
    department: "Production",
    initials: "DP",
  },
  {
    id: "user-hr",
    name: "Ishara Fernando",
    role: "hr",
    title: "HR Operations Lead",
    department: "Human Resources",
    initials: "IF",
  },
  {
    id: "user-viewer",
    name: "Management Desk",
    role: "viewer",
    title: "Executive Read-Only View",
    department: "Management",
    initials: "MD",
  },
];

export const mockWorkers: WorkerProfile[] = [
  {
    id: "worker-001",
    employeeId: "GL-1001",
    fullName: "Nirosha Kumari",
    department: "Sewing",
    roleTitle: "Sewing Operator",
    currentLineId: "line-a",
    shift: "Shift A",
    attendanceStatus: "Present",
    faceVerificationStatus: "Verified",
    fingerprintVerificationStatus: "Verified",
    finalValidationStatus: "Fully Validated",
    currentStatus: "On Line",
    skills: ["Lockstitch", "Collar attach"],
    notes: ["Consistent starter on Shift A."],
    flags: [],
    supervisorRemarks: ["Ready for multi-skill line balancing."],
    phone: "+94 77 210 4401",
    joinDate: "2024-01-12",
  },
  {
    id: "worker-002",
    employeeId: "GL-1002",
    fullName: "Suneth Perera",
    department: "Engineering",
    roleTitle: "Machine Technician",
    currentLineId: "line-b",
    shift: "Shift A",
    attendanceStatus: "Present",
    faceVerificationStatus: "Verified",
    fingerprintVerificationStatus: "Missing",
    finalValidationStatus: "Face Only",
    currentStatus: "Awaiting Validation",
    skills: ["Machine setup", "Breakdown response"],
    notes: ["Handles Line B thread tension calibration."],
    flags: ["Fingerprint device mismatch on Gate 2."],
    supervisorRemarks: ["Keep on technical standby until validation cleared."],
    phone: "+94 77 210 4402",
    joinDate: "2023-11-05",
  },
  {
    id: "worker-003",
    employeeId: "GL-1003",
    fullName: "Rashmi Mendis",
    department: "Finishing",
    roleTitle: "Finishing Operator",
    currentLineId: "line-c",
    shift: "Shift A",
    attendanceStatus: "Present",
    faceVerificationStatus: "Verified",
    fingerprintVerificationStatus: "Verified",
    finalValidationStatus: "Time Mismatch",
    currentStatus: "Awaiting Validation",
    skills: ["Thread trimming", "Final inspection"],
    notes: ["Prefers Finishing cell C2."],
    flags: ["7 minute biometric mismatch."],
    supervisorRemarks: ["Needs manual reconciliation before OT approval."],
    phone: "+94 77 210 4403",
    joinDate: "2023-08-18",
  },
  {
    id: "worker-004",
    employeeId: "GL-1004",
    fullName: "Amali Thilakarathne",
    department: "Packing",
    roleTitle: "Packing Operator",
    currentLineId: "line-d",
    shift: "Shift A",
    attendanceStatus: "Present",
    faceVerificationStatus: "Missing",
    fingerprintVerificationStatus: "Verified",
    finalValidationStatus: "Fingerprint Only",
    currentStatus: "Awaiting Validation",
    skills: ["Packing", "Barcode check"],
    notes: ["Temporary reassignment to support Line D."],
    flags: [],
    supervisorRemarks: ["Review camera angle at Gate 3."],
    phone: "+94 77 210 4404",
    joinDate: "2024-03-03",
  },
  {
    id: "worker-005",
    employeeId: "GL-1005",
    fullName: "Kasun Fernando",
    department: "Sewing",
    roleTitle: "Line Supervisor",
    currentLineId: "line-a",
    shift: "Shift A",
    attendanceStatus: "Present",
    faceVerificationStatus: "Verified",
    fingerprintVerificationStatus: "Verified",
    finalValidationStatus: "Fully Validated",
    currentStatus: "On Line",
    skills: ["Balancing", "Escalation handling"],
    notes: ["Primary floor lead for Line A."],
    flags: [],
    supervisorRemarks: ["Strong candidate for pilot smart staffing trials."],
    phone: "+94 77 210 4405",
    joinDate: "2022-09-15",
  },
  {
    id: "worker-006",
    employeeId: "GL-1006",
    fullName: "Dilini Wickrama",
    department: "Quality",
    roleTitle: "QC Checker",
    currentLineId: "line-c",
    shift: "Shift A",
    attendanceStatus: "Present",
    faceVerificationStatus: "Verified",
    fingerprintVerificationStatus: "Verified",
    finalValidationStatus: "Fully Validated",
    currentStatus: "On Line",
    skills: ["Audit inspection", "Defect tagging"],
    notes: ["Supports cross-line in-process quality checks."],
    flags: [],
    supervisorRemarks: ["Needed on Line C for rework containment."],
    phone: "+94 77 210 4406",
    joinDate: "2023-05-10",
  },
  {
    id: "worker-007",
    employeeId: "GL-1007",
    fullName: "Fathima Nizar",
    department: "Sewing",
    roleTitle: "Junior Operator",
    currentLineId: "line-b",
    shift: "Shift A",
    attendanceStatus: "Late",
    faceVerificationStatus: "Pending",
    fingerprintVerificationStatus: "Pending",
    finalValidationStatus: "Pending Validation",
    currentStatus: "Awaiting Validation",
    skills: ["Sleeve attach", "Button marking"],
    notes: ["Assigned mentor on Line B."],
    flags: [],
    supervisorRemarks: ["Monitor late arrival trend this week."],
    phone: "+94 77 210 4407",
    joinDate: "2025-02-17",
  },
  {
    id: "worker-008",
    employeeId: "GL-1008",
    fullName: "Chamodi Silva",
    department: "Sewing",
    roleTitle: "Multi-Skill Operator",
    shift: "Shift A",
    attendanceStatus: "Present",
    faceVerificationStatus: "Verified",
    fingerprintVerificationStatus: "Verified",
    finalValidationStatus: "Fully Validated",
    currentStatus: "Pending Assignment",
    skills: ["Flatlock", "Overlock", "Training support"],
    notes: ["Available for balancing understaffed lines."],
    flags: [],
    supervisorRemarks: ["Use for Line D support if packing gap grows."],
    phone: "+94 77 210 4408",
    joinDate: "2024-08-09",
  },
  {
    id: "worker-009",
    employeeId: "GL-1009",
    fullName: "Ruwan Hettiarachchi",
    department: "Finishing",
    roleTitle: "Finishing Lead",
    currentLineId: "line-c",
    shift: "Shift A",
    attendanceStatus: "Present",
    faceVerificationStatus: "Verified",
    fingerprintVerificationStatus: "Verified",
    finalValidationStatus: "Fully Validated",
    currentStatus: "On Line",
    skills: ["Line balancing", "Rework supervision"],
    notes: ["Escalation point for finishing bottlenecks."],
    flags: [],
    supervisorRemarks: ["Can receive transferred workers for faster onboarding."],
    phone: "+94 77 210 4409",
    joinDate: "2021-12-01",
  },
  {
    id: "worker-010",
    employeeId: "GL-1010",
    fullName: "Tharushi De Alwis",
    department: "Cutting",
    roleTitle: "Cutting Operator",
    shift: "Shift A",
    attendanceStatus: "On Leave",
    faceVerificationStatus: "Missing",
    fingerprintVerificationStatus: "Missing",
    finalValidationStatus: "Pending Validation",
    currentStatus: "On Leave",
    skills: ["Marker spread", "Fabric bundling"],
    notes: ["Approved annual leave until 2026-04-04."],
    flags: [],
    supervisorRemarks: ["Return to Line A support next week."],
    phone: "+94 77 210 4410",
    joinDate: "2023-03-21",
  },
  {
    id: "worker-011",
    employeeId: "GL-1011",
    fullName: "Mohamed Irfan",
    department: "Packing",
    roleTitle: "Packing Operator",
    currentLineId: "line-d",
    shift: "Shift A",
    attendanceStatus: "Absent",
    faceVerificationStatus: "Missing",
    fingerprintVerificationStatus: "Missing",
    finalValidationStatus: "Unresolved Exception",
    currentStatus: "Off Shift",
    skills: ["Folding", "Carton prep"],
    notes: ["No scan captured after roster confirmation."],
    flags: ["Attendance anomaly", "Missing worker alert open"],
    supervisorRemarks: ["Supervisor follow-up required immediately."],
    phone: "+94 77 210 4411",
    joinDate: "2024-06-02",
  },
  {
    id: "worker-012",
    employeeId: "GL-1012",
    fullName: "Sadeepa Jayawardena",
    department: "Cutting",
    roleTitle: "Cutting Assistant",
    currentLineId: "line-a",
    shift: "Shift A",
    attendanceStatus: "Present",
    faceVerificationStatus: "Verified",
    fingerprintVerificationStatus: "Verified",
    finalValidationStatus: "Fully Validated",
    currentStatus: "On Line",
    skills: ["Cut panel issue support", "Bundle tagging"],
    notes: ["Often supports pre-feed readiness for Line A."],
    flags: [],
    supervisorRemarks: ["Good transfer candidate for Line B if needed."],
    phone: "+94 77 210 4412",
    joinDate: "2024-10-10",
  },
];

export const mockLines: ProductionLineRecord[] = [
  {
    id: "line-a",
    name: "Line A",
    department: "Sewing",
    status: "Active",
    targetManpower: 18,
    actualManpower: 17,
    efficiency: 92,
    output: 438,
    targetOutput: 520,
    shift: "Shift A",
    supervisor: "Kasun Fernando",
    risk: "Stable",
  },
  {
    id: "line-b",
    name: "Line B",
    department: "Stitching",
    status: "Partial",
    targetManpower: 16,
    actualManpower: 13,
    efficiency: 81,
    output: 352,
    targetOutput: 470,
    shift: "Shift A",
    supervisor: "Dhanushka Perera",
    risk: "Watch",
    issue: "Two validation holds delaying start-up.",
  },
  {
    id: "line-c",
    name: "Line C",
    department: "Finishing",
    status: "Active",
    targetManpower: 14,
    actualManpower: 14,
    efficiency: 87,
    output: 301,
    targetOutput: 360,
    shift: "Shift A",
    supervisor: "Ruwan Hettiarachchi",
    risk: "Stable",
  },
  {
    id: "line-d",
    name: "Line D",
    department: "Packing",
    status: "Partial",
    targetManpower: 12,
    actualManpower: 9,
    efficiency: 69,
    output: 198,
    targetOutput: 310,
    shift: "Shift A",
    supervisor: "Nimali Seneviratne",
    risk: "Critical",
    issue: "Missing worker and backlog at carton sealing.",
  },
  {
    id: "line-e",
    name: "Line E",
    department: "Sample Room",
    status: "Idle",
    targetManpower: 8,
    actualManpower: 0,
    efficiency: 0,
    output: 0,
    targetOutput: 40,
    shift: "Shift A",
    supervisor: "No supervisor assigned",
    risk: "Watch",
    issue: "Standby line awaiting style changeover approval.",
  },
];

export const mockFaceEvents: FaceEvent[] = [
  { id: "face-001", workerId: "worker-001", timestamp: "2026-04-03T07:51:00", gate: "Gate 1", confidence: 98, outcome: "matched" },
  { id: "face-002", workerId: "worker-002", timestamp: "2026-04-03T08:01:00", gate: "Gate 2", confidence: 91, outcome: "matched" },
  { id: "face-003", workerId: "worker-003", timestamp: "2026-04-03T07:48:00", gate: "Gate 1", confidence: 87, outcome: "matched" },
  { id: "face-004", workerId: "worker-007", timestamp: "2026-04-03T08:20:00", gate: "Gate 1", confidence: 83, outcome: "matched" },
  { id: "face-005", workerId: "worker-008", timestamp: "2026-04-03T07:56:00", gate: "Gate 3", confidence: 97, outcome: "matched" },
  { id: "face-006", timestamp: "2026-04-03T07:59:00", gate: "Gate 4", confidence: 45, outcome: "unknown" },
];

export const mockFingerprintEvents: FingerprintEvent[] = [
  { id: "finger-001", workerId: "worker-001", timestamp: "2026-04-03T07:53:00", gate: "Gate 1", confidence: 99, outcome: "matched" },
  { id: "finger-002", workerId: "worker-003", timestamp: "2026-04-03T08:15:00", gate: "Gate 1", confidence: 86, outcome: "delayed" },
  { id: "finger-003", workerId: "worker-004", timestamp: "2026-04-03T08:07:00", gate: "Gate 3", confidence: 76, outcome: "matched" },
  { id: "finger-004", workerId: "worker-006", timestamp: "2026-04-03T07:46:00", gate: "Gate 2", confidence: 99, outcome: "matched" },
  { id: "finger-005", workerId: "worker-007", timestamp: "2026-04-03T08:28:00", gate: "Gate 1", confidence: 79, outcome: "delayed" },
  { id: "finger-006", workerId: "worker-008", timestamp: "2026-04-03T07:58:00", gate: "Gate 3", confidence: 97, outcome: "matched" },
];

export const mockValidationRecords: ValidationRecord[] = [
  {
    id: "validation-001",
    workerId: "worker-001",
    employeeId: "GL-1001",
    workerName: "Nirosha Kumari",
    date: "2026-04-03",
    shift: "Shift A",
    department: "Sewing",
    lineId: "line-a",
    faceEventTime: "2026-04-03T07:51:00",
    fingerprintEventTime: "2026-04-03T07:53:00",
    status: "Fully Validated",
    confidenceScore: 98,
    timeline: [
      { id: "vt-1", type: "face", timestamp: "2026-04-03T07:51:00", label: "Face detected", detail: "Gate 1 camera matched employee profile." },
      { id: "vt-2", type: "fingerprint", timestamp: "2026-04-03T07:53:00", label: "Fingerprint verified", detail: "Scanner accepted on first attempt." },
      { id: "vt-3", type: "validation", timestamp: "2026-04-03T07:54:00", label: "Validation completed", detail: "Worker released to Line A roster." },
    ],
  },
  {
    id: "validation-002",
    workerId: "worker-002",
    employeeId: "GL-1002",
    workerName: "Suneth Perera",
    date: "2026-04-03",
    shift: "Shift A",
    department: "Engineering",
    lineId: "line-b",
    faceEventTime: "2026-04-03T08:01:00",
    status: "Face Only",
    confidenceScore: 91,
    exceptionReason: "Fingerprint terminal on Gate 2 timed out after face match.",
    timeline: [
      { id: "vt-4", type: "face", timestamp: "2026-04-03T08:01:00", label: "Face detected", detail: "Gate 2 match confidence 91%." },
      { id: "vt-5", type: "exception", timestamp: "2026-04-03T08:03:00", label: "Exception raised", detail: "Fingerprint not captured within threshold." },
      { id: "vt-6", type: "assignment", timestamp: "2026-04-03T08:05:00", label: "Sent to holding queue", detail: "Awaiting HR validation clearance." },
    ],
  },
  {
    id: "validation-003",
    workerId: "worker-003",
    employeeId: "GL-1003",
    workerName: "Rashmi Mendis",
    date: "2026-04-03",
    shift: "Shift A",
    department: "Finishing",
    lineId: "line-c",
    faceEventTime: "2026-04-03T07:48:00",
    fingerprintEventTime: "2026-04-03T08:15:00",
    status: "Time Mismatch",
    confidenceScore: 87,
    exceptionReason: "Fingerprint recorded 27 minutes after face scan.",
    timeline: [
      { id: "vt-7", type: "face", timestamp: "2026-04-03T07:48:00", label: "Face detected", detail: "Gate 1 entry confirmed." },
      { id: "vt-8", type: "fingerprint", timestamp: "2026-04-03T08:15:00", label: "Fingerprint delayed", detail: "Scanner used after delayed queue release." },
      { id: "vt-9", type: "exception", timestamp: "2026-04-03T08:16:00", label: "Mismatch logged", detail: "Manual review required before payroll close." },
    ],
  },
  {
    id: "validation-004",
    workerId: "worker-004",
    employeeId: "GL-1004",
    workerName: "Amali Thilakarathne",
    date: "2026-04-03",
    shift: "Shift A",
    department: "Packing",
    lineId: "line-d",
    fingerprintEventTime: "2026-04-03T08:07:00",
    status: "Fingerprint Only",
    confidenceScore: 76,
    exceptionReason: "Face recognition missed due to partial occlusion.",
    timeline: [
      { id: "vt-10", type: "fingerprint", timestamp: "2026-04-03T08:07:00", label: "Fingerprint verified", detail: "Gate 3 terminal accepted scan." },
      { id: "vt-11", type: "exception", timestamp: "2026-04-03T08:08:00", label: "Face event missing", detail: "Camera lane recorded occlusion." },
    ],
  },
  {
    id: "validation-005",
    workerId: "worker-007",
    employeeId: "GL-1007",
    workerName: "Fathima Nizar",
    date: "2026-04-03",
    shift: "Shift A",
    department: "Sewing",
    lineId: "line-b",
    faceEventTime: "2026-04-03T08:20:00",
    fingerprintEventTime: "2026-04-03T08:28:00",
    status: "Pending Validation",
    confidenceScore: 83,
    exceptionReason: "Late arrival exceeds configured grace period.",
    timeline: [
      { id: "vt-12", type: "face", timestamp: "2026-04-03T08:20:00", label: "Face detected", detail: "Matched with late arrival flag." },
      { id: "vt-13", type: "fingerprint", timestamp: "2026-04-03T08:28:00", label: "Fingerprint delayed", detail: "Captured after gate supervisor intervention." },
      { id: "vt-14", type: "validation", timestamp: "2026-04-03T08:29:00", label: "Queued for review", detail: "HR must confirm attendance exception." },
    ],
  },
  {
    id: "validation-006",
    workerId: "worker-008",
    employeeId: "GL-1008",
    workerName: "Chamodi Silva",
    date: "2026-04-03",
    shift: "Shift A",
    department: "Sewing",
    faceEventTime: "2026-04-03T07:56:00",
    fingerprintEventTime: "2026-04-03T07:58:00",
    status: "Fully Validated",
    confidenceScore: 97,
    timeline: [
      { id: "vt-15", type: "face", timestamp: "2026-04-03T07:56:00", label: "Face detected", detail: "Gate 3 matched." },
      { id: "vt-16", type: "fingerprint", timestamp: "2026-04-03T07:58:00", label: "Fingerprint verified", detail: "Worker ready for flexible assignment." },
      { id: "vt-17", type: "assignment", timestamp: "2026-04-03T08:00:00", label: "Released to pool", detail: "Waiting for supervisor line assignment." },
    ],
  },
  {
    id: "validation-007",
    employeeId: "GL-1011",
    workerName: "Mohamed Irfan",
    date: "2026-04-03",
    shift: "Shift A",
    department: "Packing",
    lineId: "line-d",
    faceEventTime: "2026-04-03T07:59:00",
    status: "Unresolved Exception",
    confidenceScore: 45,
    exceptionReason: "Unknown face match and no follow-up fingerprint event.",
    timeline: [
      { id: "vt-18", type: "face", timestamp: "2026-04-03T07:59:00", label: "Unknown face event", detail: "Low confidence face event captured at Gate 4." },
      { id: "vt-19", type: "exception", timestamp: "2026-04-03T08:04:00", label: "Escalated", detail: "Missing worker alert opened for packing supervisor." },
    ],
  },
  {
    id: "validation-008",
    workerId: "worker-006",
    employeeId: "GL-1006",
    workerName: "Dilini Wickrama",
    date: "2026-04-03",
    shift: "Shift A",
    department: "Quality",
    lineId: "line-c",
    faceEventTime: "2026-04-03T07:45:00",
    fingerprintEventTime: "2026-04-03T07:46:00",
    status: "Fully Validated",
    confidenceScore: 99,
    timeline: [
      { id: "vt-20", type: "face", timestamp: "2026-04-03T07:45:00", label: "Face detected", detail: "Fast lane match complete." },
      { id: "vt-21", type: "fingerprint", timestamp: "2026-04-03T07:46:00", label: "Fingerprint verified", detail: "No discrepancy detected." },
      { id: "vt-22", type: "validation", timestamp: "2026-04-03T07:47:00", label: "Validation completed", detail: "QC audit route released." },
    ],
  },
];

export const mockLineAssignments: LineAssignmentRecord[] = [
  { id: "assign-001", workerId: "worker-001", lineId: "line-a", assignedAt: "2026-04-03T07:55:00", assignedBy: "Kasun Fernando", status: "Active" },
  { id: "assign-002", workerId: "worker-002", lineId: "line-b", assignedAt: "2026-04-03T08:05:00", assignedBy: "Dhanushka Perera", status: "Active" },
  { id: "assign-003", workerId: "worker-003", lineId: "line-c", assignedAt: "2026-04-03T08:16:00", assignedBy: "Ruwan Hettiarachchi", status: "Active" },
  { id: "assign-004", workerId: "worker-004", lineId: "line-d", assignedAt: "2026-04-03T08:09:00", assignedBy: "Nimali Seneviratne", status: "Active" },
  { id: "assign-005", workerId: "worker-008", lineId: "line-b", assignedAt: "2026-04-02T10:10:00", assignedBy: "Dhanushka Perera", status: "Transferred" },
];

export const mockTransferLogs: TransferLog[] = [
  {
    id: "transfer-001",
    workerId: "worker-008",
    sourceLineId: "line-b",
    reason: "Released to float pool for morning balancing.",
    transferredAt: "2026-04-03T08:00:00",
    transferredBy: "Dhanushka Perera",
  },
  {
    id: "transfer-002",
    workerId: "worker-006",
    sourceLineId: "line-b",
    destinationLineId: "line-c",
    reason: "Quality support moved to finishing containment area.",
    transferredAt: "2026-04-01T09:20:00",
    transferredBy: "Malithi Jayasinghe",
  },
  {
    id: "transfer-003",
    workerId: "worker-003",
    sourceLineId: "line-b",
    destinationLineId: "line-c",
    reason: "Finishing output recovery on Style 2487.",
    transferredAt: "2026-03-28T11:15:00",
    transferredBy: "Dhanushka Perera",
  },
  {
    id: "transfer-004",
    workerId: "worker-011",
    sourceLineId: "line-c",
    destinationLineId: "line-d",
    reason: "Packing peak-hour support before absenteeism spike.",
    transferredAt: "2026-03-30T13:40:00",
    transferredBy: "Malithi Jayasinghe",
  },
];

export const mockAlerts: AlertRecord[] = [
  {
    id: "alert-001",
    type: "unverified worker",
    priority: "high",
    title: "Face-only validation pending for Suneth Perera",
    description: "Engineering technician entered through Gate 2 at 08:01 AM on April 3, 2026 without matching fingerprint confirmation.",
    createdAt: "2026-04-03T08:03:00",
    status: "Open",
    assignedToUserId: "user-hr",
    workerId: "worker-002",
    lineId: "line-b",
    history: [
      { id: "ah-1", timestamp: "2026-04-03T08:03:00", user: "System", action: "Alert created from validation rule" },
    ],
  },
  {
    id: "alert-002",
    type: "missing worker",
    priority: "critical",
    title: "Packing roster missing Mohamed Irfan",
    description: "No confirmed biometric event after roster acknowledgement. Line D manpower dropped below recovery threshold.",
    createdAt: "2026-04-03T08:04:00",
    status: "Open",
    assignedToUserId: "user-supervisor",
    workerId: "worker-011",
    lineId: "line-d",
    history: [
      { id: "ah-2", timestamp: "2026-04-03T08:04:00", user: "System", action: "Missing worker alert created" },
    ],
  },
  {
    id: "alert-003",
    type: "line understaffed",
    priority: "high",
    title: "Line D understaffed against carton sealing target",
    description: "Actual manpower is 9 against a target of 12. Predicted output loss is 14% if no transfer occurs before 10:00 AM.",
    createdAt: "2026-04-03T08:10:00",
    status: "Open",
    assignedToUserId: "user-supervisor",
    lineId: "line-d",
    history: [
      { id: "ah-3", timestamp: "2026-04-03T08:10:00", user: "System", action: "Line capacity rule fired" },
    ],
  },
  {
    id: "alert-004",
    type: "line idle",
    priority: "medium",
    title: "Line E idle pending style changeover",
    description: "Sample Room line has no active manpower allocation for Shift A.",
    createdAt: "2026-04-03T07:30:00",
    status: "Read",
    lineId: "line-e",
    history: [
      { id: "ah-4", timestamp: "2026-04-03T07:30:00", user: "System", action: "Idle line notification posted" },
      { id: "ah-5", timestamp: "2026-04-03T08:00:00", user: "Malithi Jayasinghe", action: "Alert reviewed" },
    ],
  },
  {
    id: "alert-005",
    type: "delayed fingerprint",
    priority: "medium",
    title: "Fingerprint delay exceeds threshold for Fathima Nizar",
    description: "Face detected at 08:20 AM and fingerprint captured at 08:28 AM. Review grace policy before finalizing attendance.",
    createdAt: "2026-04-03T08:29:00",
    status: "Open",
    assignedToUserId: "user-hr",
    workerId: "worker-007",
    lineId: "line-b",
    history: [
      { id: "ah-6", timestamp: "2026-04-03T08:29:00", user: "System", action: "Delayed fingerprint rule triggered" },
    ],
  },
  {
    id: "alert-006",
    type: "duplicate event",
    priority: "low",
    title: "Duplicate low-confidence face event at Gate 4",
    description: "System detected a duplicate low-confidence record around roster time. Keep under review for device tuning.",
    createdAt: "2026-04-03T08:01:00",
    status: "Read",
    history: [
      { id: "ah-7", timestamp: "2026-04-03T08:01:00", user: "System", action: "Duplicate event recorded" },
      { id: "ah-8", timestamp: "2026-04-03T08:14:00", user: "Ishara Fernando", action: "Marked as seen" },
    ],
  },
  {
    id: "alert-007",
    type: "attendance anomaly",
    priority: "medium",
    title: "Rashmi Mendis shows repeated time mismatch pattern",
    description: "Three mismatched biometric windows recorded this month. Suggested audit before OT approval.",
    createdAt: "2026-04-03T08:18:00",
    status: "Open",
    assignedToUserId: "user-hr",
    workerId: "worker-003",
    lineId: "line-c",
    history: [
      { id: "ah-9", timestamp: "2026-04-03T08:18:00", user: "System", action: "Pattern anomaly surfaced by rules engine" },
    ],
  },
];

export const mockAttendanceSummaries: AttendanceSummary[] = [
  { id: "att-001", workerId: "worker-001", month: "2026-03", daysPresent: 24, daysAbsent: 1, otHours: 18, leaveDays: 0, incentive: 9500, finalTotal: 84500, validationRate: 99 },
  { id: "att-002", workerId: "worker-002", month: "2026-03", daysPresent: 23, daysAbsent: 2, otHours: 22, leaveDays: 0, incentive: 8800, finalTotal: 82300, validationRate: 91 },
  { id: "att-003", workerId: "worker-003", month: "2026-03", daysPresent: 22, daysAbsent: 1, otHours: 16, leaveDays: 2, incentive: 7200, finalTotal: 78600, validationRate: 84 },
  { id: "att-004", workerId: "worker-004", month: "2026-03", daysPresent: 24, daysAbsent: 0, otHours: 20, leaveDays: 0, incentive: 7600, finalTotal: 80100, validationRate: 88 },
  { id: "att-005", workerId: "worker-005", month: "2026-03", daysPresent: 25, daysAbsent: 0, otHours: 12, leaveDays: 0, incentive: 12000, finalTotal: 102400, validationRate: 100 },
  { id: "att-006", workerId: "worker-006", month: "2026-03", daysPresent: 24, daysAbsent: 1, otHours: 14, leaveDays: 0, incentive: 8400, finalTotal: 82400, validationRate: 99 },
  { id: "att-007", workerId: "worker-007", month: "2026-03", daysPresent: 21, daysAbsent: 3, otHours: 9, leaveDays: 1, incentive: 5400, finalTotal: 69200, validationRate: 86 },
  { id: "att-008", workerId: "worker-008", month: "2026-03", daysPresent: 25, daysAbsent: 0, otHours: 24, leaveDays: 0, incentive: 11000, finalTotal: 91400, validationRate: 100 },
  { id: "att-009", workerId: "worker-009", month: "2026-03", daysPresent: 24, daysAbsent: 1, otHours: 17, leaveDays: 0, incentive: 10200, finalTotal: 92800, validationRate: 98 },
  { id: "att-010", workerId: "worker-011", month: "2026-03", daysPresent: 20, daysAbsent: 4, otHours: 7, leaveDays: 1, incentive: 3100, finalTotal: 64100, validationRate: 72 },
];

export const mockOvertimeRecords: OvertimeRecord[] = [
  { id: "ot-001", workerId: "worker-001", date: "2026-04-01", hours: 2, approvedBy: "Kasun Fernando", lineId: "line-a" },
  { id: "ot-002", workerId: "worker-002", date: "2026-04-01", hours: 3, approvedBy: "Dhanushka Perera", lineId: "line-b" },
  { id: "ot-003", workerId: "worker-006", date: "2026-04-02", hours: 2, approvedBy: "Malithi Jayasinghe", lineId: "line-c" },
  { id: "ot-004", workerId: "worker-008", date: "2026-04-02", hours: 4, approvedBy: "Dhanushka Perera", lineId: "line-d" },
  { id: "ot-005", workerId: "worker-009", date: "2026-04-02", hours: 2.5, approvedBy: "Ruwan Hettiarachchi", lineId: "line-c" },
];

export const mockLeaveRecords: LeaveRecord[] = [
  { id: "leave-001", workerId: "worker-010", type: "Annual", startDate: "2026-04-02", endDate: "2026-04-04", days: 3, status: "Approved" },
  { id: "leave-002", workerId: "worker-007", type: "Sick", startDate: "2026-03-16", endDate: "2026-03-16", days: 1, status: "Approved" },
  { id: "leave-003", workerId: "worker-011", type: "Emergency", startDate: "2026-02-08", endDate: "2026-02-09", days: 2, status: "Approved" },
  { id: "leave-004", workerId: "worker-003", type: "Annual", startDate: "2026-03-28", endDate: "2026-03-29", days: 2, status: "Approved" },
];

export const mockIncentiveRecords: IncentiveRecord[] = [
  { id: "inc-001", workerId: "worker-001", month: "2026-03", amount: 9500, reason: "Target efficiency bonus" },
  { id: "inc-002", workerId: "worker-005", month: "2026-03", amount: 12000, reason: "Line leadership incentive" },
  { id: "inc-003", workerId: "worker-008", month: "2026-03", amount: 11000, reason: "Multi-skill support bonus" },
  { id: "inc-004", workerId: "worker-009", month: "2026-03", amount: 10200, reason: "Rework recovery incentive" },
  { id: "inc-005", workerId: "worker-006", month: "2026-03", amount: 8400, reason: "Quality containment award" },
];

export const mockAuditLogs: AuditLogEntry[] = [
  {
    id: "audit-001",
    actionType: "Worker transferred",
    user: "Malithi Jayasinghe",
    timestamp: "2026-04-01T09:20:00",
    targetEntity: "Dilini Wickrama",
    oldValue: "Line B",
    newValue: "Line C",
  },
  {
    id: "audit-002",
    actionType: "Settings changed",
    user: "Malithi Jayasinghe",
    timestamp: "2026-04-02T16:45:00",
    targetEntity: "Dual Verification Required",
    oldValue: "Disabled",
    newValue: "Disabled",
  },
  {
    id: "audit-003",
    actionType: "Validation manually resolved",
    user: "Ishara Fernando",
    timestamp: "2026-04-02T09:52:00",
    targetEntity: "Chamodi Silva",
    oldValue: "Pending Validation",
    newValue: "Fully Validated",
  },
  {
    id: "audit-004",
    actionType: "Alert resolved",
    user: "Dhanushka Perera",
    timestamp: "2026-04-02T10:18:00",
    targetEntity: "Line E idle pending style changeover",
    oldValue: "Open",
    newValue: "Read",
  },
  {
    id: "audit-005",
    actionType: "Worker assigned to line",
    user: "Dhanushka Perera",
    timestamp: "2026-04-03T08:05:00",
    targetEntity: "Suneth Perera",
    oldValue: "Holding Pool",
    newValue: "Line B",
  },
];

export const mockSmartInsights: SmartInsight[] = [
  {
    id: "insight-001",
    severity: "warning",
    lineId: "line-d",
    title: "Predicted manpower shortage on Line D by 10:00 AM",
    description: "Packing backlog and one missing worker point to a likely shortfall of 2 operators within the next 90 minutes.",
    recommendation: "Transfer one validated multi-skill operator from the pool and hold overtime approval until manpower stabilises.",
  },
  {
    id: "insight-002",
    severity: "info",
    lineId: "line-b",
    title: "Recommended reassignment: Chamodi Silva to Line B",
    description: "Chamodi has the closest skill match for sleeve attach and can cover the current validation delay on Line B.",
    recommendation: "Assign Chamodi Silva to Line B for the first half of Shift A and review at 11:00 AM.",
  },
  {
    id: "insight-003",
    severity: "warning",
    lineId: "line-c",
    title: "Suspicious attendance pattern detected for Rashmi Mendis",
    description: "Three time mismatches in the current month suggest repeated gate-to-line latency outside the normal range.",
    recommendation: "Flag for HR review and compare entry path with actual workstation login time.",
  },
  {
    id: "insight-004",
    severity: "critical",
    lineId: "line-d",
    title: "Anomaly score elevated on Packing operations",
    description: "Line D combines missing worker, delayed validation, and low output in the same shift window.",
    recommendation: "Escalate to floor supervisor and monitor alert clearance every 30 minutes.",
  },
];

export const mockAnnouncements: Announcement[] = [
  { id: "ann-001", message: "Shift A quality huddle at 10:30 AM near Line C inspection table." },
  { id: "ann-002", message: "Style 2487 carton labels updated. Use revised print batch from 09:15 AM onward." },
  { id: "ann-003", message: "Fingerprint Gate 2 terminal recalibration scheduled at 01:15 PM on April 3, 2026." },
];

export const mockSettings: SystemSettings = {
  faceRecognition: true,
  fingerprintVerification: true,
  dualValidationRequired: false,
  autoRejectUnknownFaces: true,
  manualVerificationFallback: true,
  autoMarkAbsent: true,
  morningShiftStart: "08:00",
  morningShiftEnd: "17:00",
  lateArrivalThreshold: 15,
  gracePeriod: 5,
  failedEntryAlerts: true,
  lowEfficiencyWarnings: true,
  workerAbsenceAlerts: true,
  dailySummaryReport: true,
};

export const mockReportSeries: ReportSeries = {
  weeklyAttendance: [
    { label: "Mon", value: 94, secondaryValue: 5, tertiaryValue: 2 },
    { label: "Tue", value: 92, secondaryValue: 7, tertiaryValue: 3 },
    { label: "Wed", value: 96, secondaryValue: 4, tertiaryValue: 2 },
    { label: "Thu", value: 91, secondaryValue: 6, tertiaryValue: 4 },
    { label: "Fri", value: 95, secondaryValue: 3, tertiaryValue: 2 },
    { label: "Sat", value: 88, secondaryValue: 9, tertiaryValue: 5 },
  ],
  monthlyOutput: [
    { label: "Jan", value: 18200, secondaryValue: 19000 },
    { label: "Feb", value: 19650, secondaryValue: 19500 },
    { label: "Mar", value: 20580, secondaryValue: 20000 },
    { label: "Apr", value: 12890, secondaryValue: 14000 },
  ],
  lineUtilization: [
    { label: "Line A", value: 92 },
    { label: "Line B", value: 81 },
    { label: "Line C", value: 87 },
    { label: "Line D", value: 69 },
    { label: "Line E", value: 0 },
  ],
  transferHistory: [
    { label: "Week 1", value: 5 },
    { label: "Week 2", value: 8 },
    { label: "Week 3", value: 6 },
    { label: "Week 4", value: 9 },
  ],
};

export const seedData = {
  users: mockUsers,
  workers: mockWorkers,
  lines: mockLines,
  faceEvents: mockFaceEvents,
  fingerprintEvents: mockFingerprintEvents,
  validationRecords: mockValidationRecords,
  lineAssignments: mockLineAssignments,
  transferLogs: mockTransferLogs,
  alerts: mockAlerts,
  attendanceSummaries: mockAttendanceSummaries,
  overtimeRecords: mockOvertimeRecords,
  leaveRecords: mockLeaveRecords,
  incentiveRecords: mockIncentiveRecords,
  auditLogs: mockAuditLogs,
  smartInsights: mockSmartInsights,
  announcements: mockAnnouncements,
  settings: mockSettings,
  reportSeries: mockReportSeries,
};
