package com.tradex.unionnorth.security.domain;

public enum Permission {
    EMPLOYEE_VIEW_SELF,
    EMPLOYEE_VIEW_ALL,
    EMPLOYEE_CREATE,
    EMPLOYEE_UPDATE,

    LEAVE_REQUEST,
    LEAVE_APPROVE_LEVEL_1,
    LEAVE_APPROVE_LEVEL_2,
    LEAVE_APPROVE_LEVEL_3,

    PAYROLL_VIEW,
    PAYROLL_CALCULATE,
    PAYROLL_REVIEW,
    PAYROLL_APPROVE,
    PAYROLL_LOCK,
    PAYROLL_ADJUST,

    SALARY_VIEW,
    SALARY_EDIT,
    ORGANIZATION_MANAGE,
    PAYROLL_SETUP_EDIT,

    PAYMENT_EXPORT,

    USER_VIEW,
    USER_CREATE,
    USER_UPDATE,
    USER_STATUS_MANAGE,
    USER_ROLE_ASSIGN,
    USER_CREDENTIAL_RESET,

    PRIVILEGED_ACCOUNT_MANAGE,
    SYSTEM_ADMIN_ACCESS,
    DEVELOPER_ACCESS
}
